/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.frontend.SYSTEMproductos.interfaz;

import com.project.frontend.SYSTEMproductos.controller.ControllerProducto;
import com.project.frontend.SYSTEMproductos.model.Producto;
import com.project.frontend.core.BackendException;

import java.io.IOException;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author sebastian
 */
public class ModificarProductoAdmin extends JFrame {
    private ControllerProducto controller;
    private JPanel mainPanel;
    private JPanel leftPanel;
    private JPanel rightPanel;
    public JTextField txtId;
    public JTextField txtNombre;
    public JTextField txtDescripcion;
    public JTextField txtPrecio;
    public JTextField txtCantidadEnStock;
    private JButton btnModificar;
    private JButton btnVolver;

    /**
     * Creates new form MOdificarProductoAdmin
     */
    public ModificarProductoAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controller = new ControllerProducto();
        // Ocultar el campo de búsqueda y su botón ya que no los necesitamos
        txtId.setVisible(false);
        // Hacer que el ID no sea modificable
        txtId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modificar Producto");
        setSize(1000, 650);
        setResizable(false);
        setLocationRelativeTo(null);

        mainPanel = new JPanel(new BorderLayout());
        mainPanel.setBackground(new Color(245, 245, 245));

        // Panel izquierdo (logo y título)
        leftPanel = new JPanel();
        leftPanel.setBackground(new Color(0, 122, 255));
        leftPanel.setPreferredSize(new Dimension(450, 650));
        leftPanel.setLayout(new BorderLayout());
        leftPanel.setBorder(BorderFactory.createEmptyBorder(40, 30, 40, 30));

        JLabel lblLogo = new JLabel("Invetronix");
        lblLogo.setFont(new Font("Segoe UI", Font.BOLD, 36));
        lblLogo.setForeground(Color.WHITE);
        lblLogo.setHorizontalAlignment(SwingConstants.CENTER);
        leftPanel.add(lblLogo, BorderLayout.CENTER);

        // Panel derecho (formulario)
        rightPanel = new JPanel();
        rightPanel.setBackground(new Color(245, 245, 245));
        rightPanel.setLayout(new BoxLayout(rightPanel, BoxLayout.Y_AXIS));
        rightPanel.setBorder(BorderFactory.createEmptyBorder(60, 60, 60, 60));

        // Título
        JLabel lblTitulo = new JLabel("Modificar Producto");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 36));
        lblTitulo.setForeground(new Color(33, 33, 33));
        lblTitulo.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Subtítulo
        JLabel lblSubtitulo = new JLabel("Actualiza la información del producto");
        lblSubtitulo.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        lblSubtitulo.setForeground(new Color(100, 100, 100));
        lblSubtitulo.setAlignmentX(Component.CENTER_ALIGNMENT);

        // Campo ID (oculto)
        txtId = new JTextField();
        txtId.setVisible(false);

        // Campo Nombre
        JLabel lblNombre = new JLabel("Nombre");
        lblNombre.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblNombre.setForeground(new Color(33, 33, 33));
        lblNombre.setAlignmentX(Component.LEFT_ALIGNMENT);
        txtNombre = new JTextField();
        txtNombre.setMaximumSize(new Dimension(400, 45));
        txtNombre.setBackground(Color.WHITE);
        txtNombre.setForeground(new Color(33, 33, 33));
        txtNombre.setCaretColor(new Color(0, 122, 255));
        txtNombre.setSelectedTextColor(Color.WHITE);
        txtNombre.setSelectionColor(new Color(0, 122, 255));
        txtNombre.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200)),
            BorderFactory.createEmptyBorder(5, 15, 5, 15)
        ));
        txtNombre.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // Campo Descripción
        JLabel lblDescripcion = new JLabel("Descripción");
        lblDescripcion.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblDescripcion.setForeground(new Color(33, 33, 33));
        lblDescripcion.setAlignmentX(Component.LEFT_ALIGNMENT);
        txtDescripcion = new JTextField();
        txtDescripcion.setMaximumSize(new Dimension(400, 45));
        txtDescripcion.setBackground(Color.WHITE);
        txtDescripcion.setForeground(new Color(33, 33, 33));
        txtDescripcion.setCaretColor(new Color(0, 122, 255));
        txtDescripcion.setSelectedTextColor(Color.WHITE);
        txtDescripcion.setSelectionColor(new Color(0, 122, 255));
        txtDescripcion.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200)),
            BorderFactory.createEmptyBorder(5, 15, 5, 15)
        ));
        txtDescripcion.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // Campo Precio
        JLabel lblPrecio = new JLabel("Precio");
        lblPrecio.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblPrecio.setForeground(new Color(33, 33, 33));
        lblPrecio.setAlignmentX(Component.LEFT_ALIGNMENT);
        txtPrecio = new JTextField();
        txtPrecio.setMaximumSize(new Dimension(400, 45));
        txtPrecio.setBackground(Color.WHITE);
        txtPrecio.setForeground(new Color(33, 33, 33));
        txtPrecio.setCaretColor(new Color(0, 122, 255));
        txtPrecio.setSelectedTextColor(Color.WHITE);
        txtPrecio.setSelectionColor(new Color(0, 122, 255));
        txtPrecio.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200)),
            BorderFactory.createEmptyBorder(5, 15, 5, 15)
        ));
        txtPrecio.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // Campo Cantidad en Stock
        JLabel lblStock = new JLabel("Cantidad en Stock");
        lblStock.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblStock.setForeground(new Color(33, 33, 33));
        lblStock.setAlignmentX(Component.LEFT_ALIGNMENT);
        txtCantidadEnStock = new JTextField();
        txtCantidadEnStock.setMaximumSize(new Dimension(400, 45));
        txtCantidadEnStock.setBackground(Color.WHITE);
        txtCantidadEnStock.setForeground(new Color(33, 33, 33));
        txtCantidadEnStock.setCaretColor(new Color(0, 122, 255));
        txtCantidadEnStock.setSelectedTextColor(Color.WHITE);
        txtCantidadEnStock.setSelectionColor(new Color(0, 122, 255));
        txtCantidadEnStock.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 200)),
            BorderFactory.createEmptyBorder(5, 15, 5, 15)
        ));
        txtCantidadEnStock.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // Panel de botones
        JPanel buttonsPanel = new JPanel();
        buttonsPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 20, 0));
        buttonsPanel.setBackground(new Color(245, 245, 245));

        btnModificar = new JButton("Modificar Producto");
        btnModificar.setPreferredSize(new Dimension(180, 45));
        btnModificar.setBackground(new Color(41, 128, 185));
        btnModificar.setForeground(Color.BLUE);
        btnModificar.setFont(new Font("Segoe UI", Font.BOLD, 16));
        btnModificar.setFocusPainted(false);
        btnModificar.setBorderPainted(false);
        btnModificar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnModificar.addActionListener(e -> btnModificarActionPerformed(null));

        btnVolver = new JButton("Volver");
        btnVolver.setPreferredSize(new Dimension(120, 45));
        btnVolver.setBackground(new Color(220, 53, 69));
        btnVolver.setForeground(Color.RED);
        btnVolver.setFont(new Font("Segoe UI", Font.BOLD, 16));
        btnVolver.setFocusPainted(false);
        btnVolver.setBorderPainted(false);
        btnVolver.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnVolver.addActionListener(e -> btnVolverActionPerformed(null));

        buttonsPanel.add(btnModificar);
        buttonsPanel.add(btnVolver);

        // Agregar componentes al panel derecho
        rightPanel.add(Box.createVerticalGlue());
        rightPanel.add(lblTitulo);
        rightPanel.add(Box.createVerticalStrut(15));
        rightPanel.add(lblSubtitulo);
        rightPanel.add(Box.createVerticalStrut(40));
        rightPanel.add(lblNombre);
        rightPanel.add(Box.createVerticalStrut(8));
        rightPanel.add(txtNombre);
        rightPanel.add(Box.createVerticalStrut(25));
        rightPanel.add(lblDescripcion);
        rightPanel.add(Box.createVerticalStrut(8));
        rightPanel.add(txtDescripcion);
        rightPanel.add(Box.createVerticalStrut(25));
        rightPanel.add(lblPrecio);
        rightPanel.add(Box.createVerticalStrut(8));
        rightPanel.add(txtPrecio);
        rightPanel.add(Box.createVerticalStrut(25));
        rightPanel.add(lblStock);
        rightPanel.add(Box.createVerticalStrut(8));
        rightPanel.add(txtCantidadEnStock);
        rightPanel.add(Box.createVerticalStrut(40));
        rightPanel.add(buttonsPanel);
        rightPanel.add(Box.createVerticalGlue());

        // Agregar paneles al panel principal
        mainPanel.add(leftPanel, BorderLayout.WEST);
        mainPanel.add(rightPanel, BorderLayout.CENTER);

        // Agregar panel principal al frame
        add(mainPanel);
    }

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Obtener los datos del formulario
            Long id = Long.parseLong(txtId.getText());
            String nombre = txtNombre.getText();
            String descripcion = txtDescripcion.getText();
            double precio = Double.parseDouble(txtPrecio.getText());
            int stock = Integer.parseInt(txtCantidadEnStock.getText());

            // Crear objeto Producto con los datos actualizados
            Producto producto = new Producto();
            producto.setId(id);
            producto.setNombre(nombre);
            producto.setDescripcion(descripcion);
            producto.setPrecio(precio);
            producto.setStock(stock);

            // Actualizar el producto
            controller.updateProducto(id, producto);
            
            JOptionPane.showMessageDialog(this, "Producto modificado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Volver a la ventana principal
            VentanaPrincipalAdmin ventanaPrincipal = new VentanaPrincipalAdmin();
            ventanaPrincipal.setVisible(true);
            this.dispose();
            
        } catch (BackendException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese valores numéricos válidos para precio y stock", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al modificar el producto: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {
        VentanaPrincipalAdmin ventanaPrincipal = new VentanaPrincipalAdmin();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        EventQueue.invokeLater(() -> {
            new ModificarProductoAdmin().setVisible(true);
        });
    }
}
